project:
  type: book
  output-dir: docs

book:
  title: "Logbook"
  date: "5/17/2025"
  chapters:
    - index.qmd
    - May.qmd
    - June.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

